# Generated by Django 5.2.9 on 2026-01-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_id_alter_keyword_id_alter_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='watch_interval_minutes',
        ),
        migrations.AddField(
            model_name='campaign',
            name='watch_interval_seconds',
            field=models.IntegerField(default=3600, help_text='Interval in seconds to check Reddit'),
        ),
    ]
