# Generated by Django 5.2.9 on 2026-01-02 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_campaign_watch_interval_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
                ('created_utc', models.DateTimeField()),
                ('reddit_id', models.CharField(max_length=20, unique=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_utc'],
            },
        ),
        migrations.CreateModel(
            name='RedditComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('created_utc', models.DateTimeField()),
                ('reddit_id', models.CharField(max_length=20, unique=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='campaigns.redditpost')),
            ],
            options={
                'ordering': ['-created_utc'],
            },
        ),
    ]
