# Generated by Django 5.2.9 on 2026-01-02 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_redditpost_redditcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_fetch_interval', models.IntegerField(default=300, help_text='Seconds between fetching posts')),
                ('comment_fetch_interval', models.IntegerField(default=360, help_text='Seconds between fetching comments')),
                ('last_post_id', models.CharField(blank=True, help_text='Fullname of last fetched post', max_length=20, null=True)),
                ('last_comment_id', models.CharField(blank=True, help_text='Fullname of last fetched comment', max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='watch_interval_seconds',
        ),
        migrations.RemoveField(
            model_name='redditcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='redditpost',
            name='campaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='match_interval_seconds',
            field=models.IntegerField(default=3600, help_text='Interval in seconds to match keywords'),
        ),
        migrations.AddField(
            model_name='redditcomment',
            name='link_id',
            field=models.CharField(default='t3_00000', help_text='ID of the post this comment belongs to', max_length=20),
        ),
        migrations.AddField(
            model_name='redditcomment',
            name='permalink',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='redditcomment',
            name='subreddit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='over_18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='permalink',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='selftext',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='stickied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='subreddit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='redditcomment',
            name='created_utc',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='created_utc',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='CampaignMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_text', models.TextField(help_text='The snippet of text that matched')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='campaigns.campaign')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='campaigns.redditcomment')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='campaigns.keyword')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='campaigns.redditpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'comment'), ('campaign', 'post')},
            },
        ),
    ]
