# Generated by Django 5.2.9 on 2026-01-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_globalsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditcomment',
            name='link_id',
            field=models.CharField(help_text='ID of the post this comment belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='redditcomment',
            name='permalink',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='redditcomment',
            name='subreddit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='permalink',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit',
            field=models.CharField(max_length=100),
        ),
    ]
