# Generated by Django 5.2.9 on 2026-01-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_redditcomment_link_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='empty_comment_fetch_count',
            field=models.IntegerField(default=0, help_text='Consecutive empty comment fetches (for stale ID detection)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='empty_post_fetch_count',
            field=models.IntegerField(default=0, help_text='Consecutive empty post fetches (for stale ID detection)'),
        ),
    ]
