# Generated by Django 5.2.9 on 2026-01-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_globalsettings_empty_comment_fetch_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='last_processed_comment_id',
            field=models.BigIntegerField(default=0, help_text='Last processed RedditComment internal ID'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_processed_post_id',
            field=models.BigIntegerField(default=0, help_text='Last processed RedditPost internal ID'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignmatch',
            unique_together={('campaign', 'comment', 'keyword'), ('campaign', 'post', 'keyword')},
        ),
    ]
