# Generated by Django 5.2.9 on 2026-01-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_last_processed_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditcomment',
            name='permalink',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='permalink',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
